import { Category } from "../models/category.model.js";

const ProductsData = [
    {
      id: 1,
      product: "Maggi",
      price: 430,
      qty: 43,
      thresholdValue: 12,
      expiry: "11/12/22",
      avl: "In-stock",
    },
    {
      id: 2,
      product: "Bru",
      price: 257,
      qty: 22,
      thresholdValue: 12,
      expiry: "21/12/22",
      avl: "Out of stock",
    },
    {
      id: 3,
      product: "Coca cola",
      price: 205,
      qty: 41,
      thresholdValue: 10,
      expiry: "11/11/24",
      avl: "Low stock",
    },
    {
      id: 4,
      product: "Pepsi",
      price: 220,
      qty: 35,
      thresholdValue: 15,
      expiry: "12/10/23",
      avl: "In-stock",
    },
    {
      id: 5,
      product: "KitKat",
      price: 150,
      qty: 50,
      thresholdValue: 20,
      expiry: "15/09/23",
      avl: "In-stock",
    },
  ];
  
  const SuppliersData = [
    {
      id: 1,
      supplierName: "Richard Martin",
      product: "Kit kat",
      contact: "7687764556",
      email: "richard@gmail.com",
      type: "Taking Return",
      stockInTransit: 13,
    },
    {
      id: 2,
      supplierName: "Tom Homan",
      product: "Maaza",
      contact: "9667754096",
      email: "tomhoman@gmail.com",
      type: "Taking Return",
      stockInTransit: null,
    },
    {
      id: 3,
      supplierName: "Veandir",
      product: "Dairy Milk",
      contact: "9668754096",
      email: "veandir@gmail.com",
      type: "Not Taking Return",
      stockInTransit: null,
    },
    {
      id: 4,
      supplierName: "Charin",
      product: "Tomato",
      contact: "9267545457",
      email: "charin@gmail.com",
      type: "Taking Return",
      stockInTransit: 12,
    },
    {
      id: 5,
      supplierName: "Hoffman",
      product: "Milk Bikis",
      contact: "9367546531",
      email: "hoffman@gmail.com",
      type: "Taking Return",
      stockInTransit: null,
    },
    {
      id: 6,
      supplierName: "Fainden Juke",
      product: "Marie Gold",
      contact: "9667545982",
      email: "fainden@gmail.com",
      type: "Not Taking Return",
      stockInTransit: 9,
    },
    {
      id: 7,
      supplierName: "Martin",
      product: "Saffola",
      contact: "9867545457",
      email: "martin@gmail.com",
      type: "Taking Return",
      stockInTransit: null,
    },
    {
      id: 8,
      supplierName: "Joe Nike",
      product: "Good day",
      contact: "9567545769",
      email: "joenike@gmail.com",
      type: "Taking Return",
      stockInTransit: null,
    },
    {
      id: 9,
      supplierName: "Dender Luke",
      product: "Apple",
      contact: "9667545980",
      email: "dender@gmail.com",
      type: "Not Taking Return",
      stockInTransit: 7,
    },
    {
      id: 10,
      supplierName: "Fainden Juke",
      product: "Marie Gold",
      contact: "9667545982",
      email: "fainden@gmail.com",
      type: "Not Taking Return",
      stockInTransit: 9,
    },
    {
      id: 11,
      supplierName: "Fainden Juke",
      product: "Marie Gold",
      contact: "9667545982",
      email: "fainden@gmail.com",
      type: "Not Taking Return",
      stockInTransit: 9,
    },
    {
      id: 12,
      supplierName: "Richard Martin",
      product: "Kit kat",
      contact: "7687764556",
      email: "richard@gmail.com",
      type: "Taking Return",
      stockInTransit: 13,
    },
    {
      id: 13,
      supplierName: "Fainden Juke",
      product: "Marie Gold",
      contact: "9667545982",
      email: "fainden@gmail.com",
      type: "Not Taking Return",
      stockInTransit: 9,
    },
    {
      id: 14,
      supplierName: "Veandir",
      product: "Dairy Milk",
      contact: "9668754096",
      email: "veandir@gmail.com",
      type: "Not Taking Return",
      stockInTransit: null,
    },
    {
      id: 15,
      supplierName: "Richard Martin",
      product: "Kit kat",
      contact: "7687764556",
      email: "richard@gmail.com",
      type: "Taking Return",
      stockInTransit: 13,
    },
    {
      id: 16,
      supplierName: "Tom Homan",
      product: "Maaza",
      contact: "9667754096",
      email: "tomhoman@gmail.com",
      type: "Taking Return",
      stockInTransit: null,
    },
    {
      id: 17,
      supplierName: "Veandir",
      product: "Dairy Milk",
      contact: "9668754096",
      email: "veandir@gmail.com",
      type: "Not Taking Return",
      stockInTransit: null,
    },
    {
      id: 18,
      supplierName: "Charin",
      product: "Tomato",
      contact: "9267545457",
      email: "charin@gmail.com",
      type: "Taking Return",
      stockInTransit: 12,
    },
    {
      id: 19,
      supplierName: "Hoffman",
      product: "Milk Bikis",
      contact: "9367546531",
      email: "hoffman@gmail.com",
      type: "Taking Return",
      stockInTransit: null,
    },
    {
      id: 20,
      supplierName: "Fainden Juke",
      product: "Marie Gold",
      contact: "9667545982",
      email: "fainden@gmail.com",
      type: "Not Taking Return",
      stockInTransit: 9,
    },
    {
      id: 21,
      supplierName: "Martin",
      product: "Saffola",
      contact: "9867545457",
      email: "martin@gmail.com",
      type: "Taking Return",
      stockInTransit: null,
    },
    {
      id: 22,
      supplierName: "Joe Nike",
      product: "Good day",
      contact: "9567545769",
      email: "joenike@gmail.com",
      type: "Taking Return",
      stockInTransit: null,
    },
    {
      id: 23,
      supplierName: "Dender Luke",
      product: "Apple",
      contact: "9667545980",
      email: "dender@gmail.com",
      type: "Not Taking Return",
      stockInTransit: 7,
    },
    {
      id: 24,
      supplierName: "Fainden Juke",
      product: "Marie Gold",
      contact: "9667545982",
      email: "fainden@gmail.com",
      type: "Not Taking Return",
      stockInTransit: 9,
    },
    {
      id: 25,
      supplierName: "Fainden Juke",
      product: "Marie Gold",
      contact: "9667545982",
      email: "fainden@gmail.com",
      type: "Not Taking Return",
      stockInTransit: 9,
    },
  ];
  
  const OrdersData = [
    {
      id: 1,
      productName: "Maggi",
      orderValue: "₹4306",
      qty: "43 Packets",
      orderId: "7535",
      expectedDelivery: "11/12/22",
      status: "Delayed",
    },
    {
      id: 2,
      productName: "Bru",
      orderValue: "₹2557",
      qty: "22 Packets",
      orderId: "5724",
      expectedDelivery: "21/12/22",
      status: "Confirmed",
    },
    {
      id: 3,
      productName: "Coca cola",
      orderValue: "₹2015",
      qty: "41 Packets",
      orderId: "2775",
      expectedDelivery: "11/11/24",
      status: "Returned",
    },
    {
      id: 4,
      productName: "Maggi",
      orderValue: "₹4130",
      qty: "43 Packets",
      orderId: "1256",
      expectedDelivery: "11/12/22",
      status: "Out for delivery",
    },
    {
      id: 5,
      productName: "Bru",
      orderValue: "₹257",
      qty: "22 Packets",
      orderId: "3412",
      expectedDelivery: "21/12/22",
      status: "Returned",
    },
    {
      id: 6,
      productName: "Coca cola",
      orderValue: "₹205",
      qty: "41 Packets",
      orderId: "1230",
      expectedDelivery: "11/11/24",
      status: "Out for delivery",
    },
    {
      id: 7,
      productName: "Maggi",
      orderValue: "₹430",
      qty: "43 Packets",
      orderId: "6612",
      expectedDelivery: "11/12/22",
      status: "Delayed",
    },
    {
      id: 8,
      productName: "Bru",
      orderValue: "₹257",
      qty: "22 Packets",
      orderId: "1432",
      expectedDelivery: "21/12/22",
      status: "Confirmed",
    },
    {
      id: 9,
      productName: "Coca cola",
      orderValue: "₹205",
      qty: "41 Packets",
      orderId: "4510",
      expectedDelivery: "11/11/24",
      status: "Delayed",
    },
    {
      id: 10,
      productName: "Maggi",
      orderValue: "₹4306",
      qty: "43 Packets",
      orderId: "7535",
      expectedDelivery: "11/12/22",
      status: "Delayed",
    },
    {
      id: 11,
      productName: "Bru",
      orderValue: "₹2557",
      qty: "22 Packets",
      orderId: "5724",
      expectedDelivery: "21/12/22",
      status: "Confirmed",
    },
    {
      id: 12,
      productName: "Coca cola",
      orderValue: "₹2015",
      qty: "41 Packets",
      orderId: "2775",
      expectedDelivery: "11/11/24",
      status: "Returned",
    },
    {
      id: 13,
      productName: "Maggi",
      orderValue: "₹4130",
      qty: "43 Packets",
      orderId: "1256",
      expectedDelivery: "11/12/22",
      status: "Out for delivery",
    },
    {
      id: 14,
      productName: "Bru",
      orderValue: "₹257",
      qty: "22 Packets",
      orderId: "3412",
      expectedDelivery: "21/12/22",
      status: "Returned",
    },
    {
      id: 15,
      productName: "Coca cola",
      orderValue: "₹205",
      qty: "41 Packets",
      orderId: "1230",
      expectedDelivery: "11/11/24",
      status: "Out for delivery",
    },
    {
      id: 16,
      productName: "Maggi",
      orderValue: "₹430",
      qty: "43 Packets",
      orderId: "6612",
      expectedDelivery: "11/12/22",
      status: "Delayed",
    },
    {
      id: 17,
      productName: "Bru",
      orderValue: "₹257",
      qty: "22 Packets",
      orderId: "1432",
      expectedDelivery: "21/12/22",
      status: "Confirmed",
    },
    {
      id: 18,
      productName: "Coca cola",
      orderValue: "₹205",
      qty: "41 Packets",
      orderId: "4510",
      expectedDelivery: "11/11/24",
      status: "Delayed",
    },
    {
      id: 19,
      productName: "Maggi",
      orderValue: "₹4306",
      qty: "43 Packets",
      orderId: "7535",
      expectedDelivery: "11/12/22",
      status: "Delayed",
    },
    {
      id: 20,
      productName: "Bru",
      orderValue: "₹2557",
      qty: "22 Packets",
      orderId: "5724",
      expectedDelivery: "21/12/22",
      status: "Confirmed",
    },
    {
      id: 21,
      productName: "Coca cola",
      orderValue: "₹2015",
      qty: "41 Packets",
      orderId: "2775",
      expectedDelivery: "11/11/24",
      status: "Returned",
    },
    {
      id: 22,
      productName: "Maggi",
      orderValue: "₹4130",
      qty: "43 Packets",
      orderId: "1256",
      expectedDelivery: "11/12/22",
      status: "Out for delivery",
    },
    {
      id: 23,
      productName: "Bru",
      orderValue: "₹257",
      qty: "22 Packets",
      orderId: "3412",
      expectedDelivery: "21/12/22",
      status: "Returned",
    },
    {
      id: 24,
      productName: "Coca cola",
      orderValue: "₹205",
      qty: "41 Packets",
      orderId: "1230",
      expectedDelivery: "11/11/24",
      status: "Out for delivery",
    },
    {
      id: 25,
      productName: "Maggi",
      orderValue: "₹430",
      qty: "43 Packets",
      orderId: "6612",
      expectedDelivery: "11/12/22",
      status: "Delayed",
    },
    {
      id: 26,
      productName: "Bru",
      orderValue: "₹257",
      qty: "22 Packets",
      orderId: "1432",
      expectedDelivery: "21/12/22",
      status: "Confirmed",
    },
    {
      id: 27,
      productName: "Coca cola",
      orderValue: "₹205",
      qty: "41 Packets",
      orderId: "4510",
      expectedDelivery: "11/11/24",
      status: "Delayed",
    },
    {
      id: 28,
      productName: "Maggi",
      orderValue: "₹4306",
      qty: "43 Packets",
      orderId: "7535",
      expectedDelivery: "11/12/22",
      status: "Delayed",
    },
  ];
  
  const inventoryData = {
    categories: {
      count: 14,
      lastUpdated: "Last 7 days",
    },
    totalProducts: {
      count: 868,
      lastUpdated: "Last 7 days",
      revenue: "₹ 25000",
    },
    mostUsed: {
      count: 5,
      lastUpdated: "Last 7 days",
      cost: "₹ 2500",
    },
    lowStocks: {
      ordered: 12,
      notInStock: 2,
    },
  };
  
  
const initData = async function(){
    await Category.insertMany([
        { category: "Grocery" },
        { category: "Stationery" },
        { category: "Electronics" },
        { category: "Cleaning Supplies" },
        { category: "Office Furniture" },
        { category: "Kitchen Supplies" },
        { category: "Personal Care" },
        { category: "Computer Accessories" },
        { category: "Safety and Security" },
        { category: "Tools and Equipment" }
    ])
}

export  {initData}; 